
import type { Metadata } from "next";
import { Inter, Archivo, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "@/components/provider/Provider";
const archivo = Archivo({subsets:["latin"], weight: ["200", "400", "500", "700"], variable: "--font-achivo"})

export const metadata: Metadata = {
  title: "Sneakers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className}`}>
        <ReduxProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
